const productNames = {
  hiking: [
    "TrailBlazer Pro Ventilator",
    "Alpine Ascent Shell",
    "Mountain Scout Expedition",
    "Wilderness Navigator Elite",
    "Summit Seeker Ultralight",
    "PathFinder Advance Trek",
    "Ridge Runner Performance",
    "TerrainMaster Endurance",
    "BackCountry Explorer Pro",
    "Peak Performance Venture",
  ],
  skiing: [
    "PowderPro Carve Elite",
    "SnowMaster Avalanche",
    "Alpine Descent Pro",
    "FrostGuard Extreme",
    "GlacierTech Performance",
    "Nordic Patrol Elite",
    "IceBreaker Advance",
    "SlalomMaster Pro",
    "WinterForce Expedition",
    "PeakRider Supreme",
  ],
  climbing: [
    "RockMaster Flex Pro",
    "CliffHanger Elite",
    "BoulderTech Advance",
    "PeakScaler Supreme",
    "AlpineAce Performance",
    "CragMaster Pro",
    "AscentPro Ultralight",
    "VerticalEdge Elite",
    "SummitSeeker Advance",
    "ClimbTech Expedition",
  ],
  running: [
    "SpeedVent Pro Runner",
    "TrailBurst Elite",
    "WindRunner Advance",
    "MarathonMaster Pro",
    "SprintTech Performance",
    "EnduranceElite Pro",
    "RacePace Ultralight",
    "TrackStar Advance",
    "RunnersPro Elite",
    "SwiftMotion Supreme",
  ],
  cycling: [
    "VeloTech Pro Elite",
    "CyclonePro Advance",
    "SpeedMaster Aero",
    "RiderElite Performance",
    "BikeRunner Supreme",
    "PedalPro Expedition",
    "CycleForce Elite",
    "TrailBiker Advance",
    "VelocityPro Master",
    "RacePace Cycling Pro",
  ],
  casual: [
    "UrbanExplorer Elite",
    "CityTrekker Pro",
    "StreetStyle Advance",
    "MetroVent Performance",
    "TownRunner Supreme",
    "UrbanPro Comfort",
    "CityScape Elite",
    "StreetMaster Pro",
    "MetroFlex Advance",
    "UrbanMotion Elite",
  ],
};

module.exports = productNames;
